### ISSUE TITLE
[1pt] Create basic structure for Missions - Setup

### ISSUE THREAD

**Issue by clintonjosephs** [clintonjosephs/Space-traveler#20]
- Create a route and a view component. Use `<NavLink />` for the page navigation links and style active class to indicate which section/page the user is currently on (underline active navigation link).
- Create a directory for all Redux state slice files.

**Comment by guerreiropedr0** [comment]
Here is the pull request for this issue - https://github.com/clintonjosephs/Space-traveler/pull/30
