### ISSUE TITLE
Space-traveller - Kanban board setup

### ISSUE THREAD

**Issue by clintonjosephs** [clintonjosephs/Space-traveler#25]
Hello 😄,

Kindly see below, a link to our kanban board and cards assignments.

[Kanban board](https://github.com/clintonjosephs/Space-traveller/projects/1)

We are two in the group for the project

**Comment by julie-ify** [comment]
Hi @clintonjosephs and @guerreiropedr0, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by clintonjosephs** [comment]
Thank you so much for your feedback
