### ISSUE TITLE
[1pt] Switch badges for Missions - Conditional components

### ISSUE THREAD

**Issue by clintonjosephs** [clintonjosephs/Space-traveler#6]
Missions that the user has joined already should show a badge "Active Member" instead of the default "NOT A MEMBER" and a button "Leave Mission" instead of the "Join Mission" button (as per design).

Use the React conditional rendering syntax:
```javascript
{rocket.reserved && ( 
    // render Cancel Rocket button
)}
```

**Comment by clintonjosephs** [comment]
Here is the PR for this issue https://github.com/clintonjosephs/Space-traveler/pull/39

**Comment by guerreiropedr0** [comment]
The pull request for this issue - https://github.com/clintonjosephs/Space-traveler/pull/41
